[package]
name = "ibc-eureka-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
serde = { workspace = true }
ibc-eureka-solidity = { workspace = true }
sp1-ics07-tendermint-solidity = { workspace = true }
