[workspace]
members = [
    "voyager/client-update/sp1-ics07",
]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/srdtrk/ibc-eureka-plugins"
authors    = ["srdtrk <srdtrk.b@gmail.com>"]
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", default-features = false }

sp1-ics07-tendermint-solidity = { git = "https://github.com/cosmos/sp1-ics07-tendermint", rev = "9ee431733a1b4645024e348eca7f8fdd3c8e17c5" }

voyager-message = { git = "https://github.com/srdtrk/union", branch = "serdar/3143-fix-unionlabs" }
voyager-vm = { git = "https://github.com/srdtrk/union", branch = "serdar/3143-fix-unionlabs" }
