[package]
name = "ibc-eureka-union-extensions"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
unionlabs = { workspace = true }
