[package]
name = "ibc-eureka-union-ext"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
unionlabs = { workspace = true }
sp1-ics07-tendermint-solidity = { workspace = true, features = ["rpc"] }
